#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=d)

echo "$files" | grep -E "\.(jsx?|tsx?)$" | xargs npx eslint

if [ $? -ne 0 ]; then
  exit $?
fi

echo "$files" | grep -E "\.(html|svg)$" | xargs npx prettier --write
echo "$files" | xargs git add
